[build-system]
requires = ["setuptools>=61.0", "setuptools-scm", "mypy==1.13.0", "numpy==2.1.2"]
build-backend = "setuptools.build_meta"

[project]
name = "cpscheduler"
version = "0.1.0"
authors = [
  { name="Daniel Gardin", email="gardin.dan@gmail.com" },
]
description = "Solving Scheduling Problems with Constraint Programming and Reinforcement Learning"
readme = "README.md"
requires-python = ">=3.11"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[tool.setuptools]
packages = ["cpscheduler"]