[build-system]
requires = [
    "setuptools>=61.0",
    "setuptools-scm",
    "wheel",
    "mypy>=1.13.0",
    "mypy_extensions",
    "tomli; python_version<'3.11'",
    "multimethod >= 2.0.0",
]
build-backend = "setuptools.build_meta"

[project]
name = "cpscheduler"
version = "0.5.0"
authors = [
    { name="Daniel Gardin", email="gardin.dan@gmail.com" },
]
description = "Solving Scheduling Problems with Constraint Programming and Reinforcement Learning"
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "MIT AND (Apache-2.0 OR BSD-2-Clause)",
    "Operating System :: OS Independent",
]
dependencies = [
    "mypy_extensions",
    "colorlog==6.9.0"
]

[project.optional-dependencies]

gym = [
    "gymnasium >= 1.1.1",
    "pandas >= 2.1.3",
    "plotly>=6.2.0",
    "colorcet>=3.1.0"
]

rl = [
    "cpscheduler[gym]",
    "torch >= 2.0.1",
    "tensordict >= 0.7.0",
    "tqdm >= 4.67.1",
    "wandb >= 0.21.0",
    "tensorboard >= 2.19.0",
    "tqdm >= 4.67.1",
    "tyro >= 0.9.26"
]

solver = [
    "pulp >= 2.7.0",
    "nest_asyncio>=1.6.0",
    "multimethod >= 2.0.0",
]

all = [
    "cpscheduler[gym, rl, solver]"
]

dev = [
    "cpscheduler[all]",
    "pytest >= 7.1.3",
    "mypy >= 1.13.0",
    "black >= 25.1.0"
]

[tool.setuptools]
packages = ["cpscheduler"]
