[build-system]
requires = [
    "setuptools>=61.0",
    "setuptools-scm",
    "wheel",
    "gymnasium >= 1.1.1",
    "mypy>=1.13.0",
    "mypy_extensions",
    "tomli; python_version<'3.11'",
]
build-backend = "setuptools.build_meta"

[project]
name = "cpscheduler"
version = "0.4.0"
authors = [
    { name="Daniel Gardin", email="gardin.dan@gmail.com" },
]
description = "Solving Scheduling Problems with Constraint Programming and Reinforcement Learning"
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "MIT AND (Apache-2.0 OR BSD-2-Clause)",
    "Operating System :: OS Independent",
]
dependencies = [
    "gymnasium >= 1.1.1",
    "multimethod >= 2.0",
    "mypy >= 1.13.0",
    "mypy_extensions >= 1.0.0",
    "pandas >= 2.2.3" # TODO: Remove this dependency
]

[project.optional-dependencies]
rl = [
    "torch >= 2.0.1",
    "tensordict >= 0.7.0",
    "tqdm >= 4.67.1",
    "wandb >= 0.21.0",
    "tensorboard >= 2.19.0",
    "tqdm >= 4.67.1"
]

tests = [
    "pytest >= 7.1.3",
    "torch >= 2.0.1",
]

solver = [
    "pulp >= 2.7.0"
]


[tool.setuptools]
packages = ["cpscheduler"]

[tool.mypy]
strict = true
pretty = true
ignore_missing_imports = true
disallow_untyped_defs = true
warn_unused_ignores = false
disallow_subclassing_any = false
disable_error_code = ["type-abstract"]

[[tool.mypy.overrides]]
module = "torch.*"
ignore_missing_imports = true
follow_imports = "skip"
follow_imports_for_stubs = true
disallow_untyped_calls = false

[[tool.mypy.overrides]]
module = "pulp.*"
ignore_missing_imports = true
follow_imports = "skip"
follow_imports_for_stubs = true
disallow_untyped_calls = false

[[tool.tensordict.overrides]]
module = "pulp.*"
ignore_missing_imports = true
follow_imports = "skip"
follow_imports_for_stubs = true
disallow_untyped_calls = false
