[build-system]
requires = ["setuptools>=61.0", "setuptools-scm", "wheel", "mypy==1.13.0", "mypy_extensions", "numpy==2.1.2"]
build-backend = "setuptools.build_meta"

[project]
name = "cpscheduler"
version = "0.2.3"
authors = [
    { name="Daniel Gardin", email="gardin.dan@gmail.com" },
]
description = "Solving Scheduling Problems with Constraint Programming and Reinforcement Learning"
readme = "README.md"
requires-python = ">=3.11"
classifiers = [
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[tool.setuptools]
packages = ["cpscheduler"]

[tool.mypy]
python_version = "3.11"
plugins = ["numpy.typing.mypy_plugin"]
strict = true
pretty = true
ignore_missing_imports = true
disallow_untyped_defs = true
warn_unused_ignores = false
disallow_subclassing_any = false
disable_error_code = ["type-abstract"]

[[tool.mypy.overrides]]
module = "torch.*"
ignore_missing_imports = true
follow_imports = "skip"
follow_imports_for_stubs = true