"""Protocol and type helpers for environment configuration.

This module defines lightweight protocols and typed dictionaries used across
the environment to describe metrics, instances, and configuration options.
"""

from collections.abc import Hashable, Iterable, Iterator
from typing import TYPE_CHECKING, Any, Protocol, overload, runtime_checkable

from typing_extensions import TypedDict, TypeIs, TypeVar

if TYPE_CHECKING:
    from cpscheduler.environment.state import ScheduleState

_T = TypeVar("_T")
_T_co = TypeVar("_T_co", covariant=True, default=Any)


class Metric(Protocol[_T_co]):
    """Metric callable protocol.

    A metric is any callable that receives the current `ScheduleState` and
    returns a value for logging or evaluation.

    Methods
    -------
    __call__(state)
        Compute a metric value from the provided state.

    """

    def __call__(self, state: "ScheduleState") -> _T_co:
        """Compute a metric value from a schedule state.

        Parameters
        ----------
        state : ScheduleState
            Current environment state.

        Returns
        -------
        _T_co
            Metric value.

        """
        ...


@runtime_checkable
class ArrayLike(Protocol[_T]):
    """Minimal protocol for array-like objects.

    This is an extension of Iterable that implements `tolist`.

    Methods
    -------
    __iter__()
        Iterate over the array.

    tolist()
        Return a list equivalent to the array.

    """

    def __iter__(self) -> Iterator[_T]:
        """Iterate over the array."""
        ...

    def tolist(self) -> list[_T]:
        """Return a list equivalent to the array."""
        ...


_K = TypeVar("_K", bound=Hashable)
_V = TypeVar("_V", covariant=True, default=Any)


class DataFrameLike(Protocol[_K, _V]):
    """Minimal protocol for data frame-like instances.

    The interface supports column-style access and iteration over column keys.
    Formally, the protocol requires that every key yielded by `__iter__` is
    valid for `__getitem__`.

    Methods
    -------
    __getitem__(key)
        Return a column-like sequence for the given key.

    __iter__()
        Iterate over column keys.

    """

    def __getitem__(self, key: _K, /) -> _V:
        """Return a column-like sequence for the provided key."""
        ...

    def __iter__(self) -> Iterator[_K]:
        """Iterate over available column keys."""
        ...


@overload
def is_dataframe_like(
    obj: Any, key_T: type[_T], value_T: None = None
) -> TypeIs[DataFrameLike[_T, Any]]: ...


@overload
def is_dataframe_like(
    obj: Any, *, key_T: None = None, value_T: type[_T]
) -> TypeIs[DataFrameLike[Any, _T]]: ...


@overload
def is_dataframe_like(
    obj: Any, key_T: type[_K], value_T: type[_V]
) -> TypeIs[DataFrameLike[_K, _V]]: ...


def is_dataframe_like(
    obj: Any, key_T: type | None = None, value_T: type | None = None
) -> TypeIs[DataFrameLike[Any, Any]]:
    """Check if an object conforms to the DataFrameLike protocol.

    Note: This is a runtime check, and the iterable generated by `__iter__`
    will be consumed.
    """
    try:
        for key in obj:
            obj[key]

        if key_T is not None:
            return all(isinstance(k, key_T) for k in obj)

        if value_T is not None:
            return all(isinstance(obj[k], value_T) for k in obj)

        return True

    except (KeyError, TypeError, IndexError):
        return False


Instance_T = DataFrameLike[str, Any]

InstanceTypes = Instance_T | Iterable[Instance_T]  # Task-instance data


def ensure_iterable(instance: InstanceTypes) -> Iterable[Instance_T]:
    """Ensure that the instance data is iterable."""
    if is_dataframe_like(instance, str):
        return (instance,)

    return instance


@runtime_checkable
class InstanceGenerator(Protocol):
    """Protocol for components that generate instances from a spec.

    Methods
    -------
    sample(seed=None)
        Sample a new instance (optionally seeded).

    """

    def sample(self, seed: int | None = None) -> InstanceTypes:
        """Sample a new instance.

        Parameters
        ----------
        seed : int | None, optional
            Random seed for reproducibility.

        Returns
        -------
        InstanceTypes
            Sampled instance data.

        """
        ...


InfoType = dict[str, Any]


class InstanceConfig(TypedDict, total=False):
    """Configuration for loading an instance.

    Attributes
    ----------
    instance : InstanceTypes
        Specific instance data to load.

    instance_generator : InstanceGenerator
        Generator used to sample an instance at reset.

    seed : int
        Seed for the instance generator.

    """

    instance: InstanceTypes
    instance_generator: InstanceGenerator
    seed: int


Options = dict[str, Any] | InstanceConfig
