"""Implementation of events for the discrete event simulation environment."""

from __future__ import annotations

from typing import TYPE_CHECKING

from typing_extensions import Self, override

from cpscheduler.environment.backend.des.base import SimulationEvent
from cpscheduler.environment.constants import (
    GLOBAL_MACHINE_ID,
    MachineID,
    TaskID,
    Time,
)

if TYPE_CHECKING:
    from cpscheduler.environment.backend.des.des import DESBackend
    from cpscheduler.environment.state import ScheduleState


def select_machine(
    state: ScheduleState, task_id: TaskID, time: Time
) -> MachineID:
    """Select an available machine using a simple heuristic."""
    machines = state.get_machines(task_id)

    for machine in sorted(machines):
        if state.can_start(time, task_id, machine):
            return machine

    raise ValueError(f"No available machines for task {task_id}.")


class ExecuteEvent(SimulationEvent):
    """Event representing the execution of a task on a machine.

    This event triggers the start of a task's execution on a specific machine.
    It blocks the schedule until the task starts executing, ensuring that the task's
    execution is properly accounted for in the schedule's state.

    Resolution
    ----------
    If the machine_id is set to GLOBAL_MACHINE_ID, and there is only one machine
    available for the task, the event will be automatically resolved to that machine,
    creating another ExecuteEvent with the resolved machine_id.

    """

    blocking = True

    task_id: TaskID
    machine_id: MachineID

    def __init__(
        self, task_id: TaskID, machine_id: MachineID = GLOBAL_MACHINE_ID
    ) -> None:
        """Initialize the ExecuteEvent.

        Parameters
        ----------
        task_id: TaskID
            The ID of the task to be executed.

        machine_id: MachineID, optional
            The ID of the machine on which to execute the task. If not specified,
            the event will attempt to resolve the machine at runtime.

        """
        self.task_id = task_id
        self.machine_id = machine_id

    @override
    def resolve(self, state: ScheduleState) -> Self:
        machine_id = self.machine_id
        task_id = self.task_id
        task_machines = state.get_machines(task_id)

        if machine_id != GLOBAL_MACHINE_ID:
            if machine_id not in task_machines:
                raise ValueError(
                    f"Machine {machine_id} is not available for task {task_id}"
                )

        elif len(task_machines) == 1:
            # Statically resolve the machine if there is only one option
            resolved_machine = next(iter(task_machines))
            return type(self)(task_id, resolved_machine)

        return self

    @override
    def earliest_time(self, state: ScheduleState) -> Time:
        return state.get_start_lb(self.task_id, self.machine_id)

    @override
    def is_ready(self, state: ScheduleState, backend: DESBackend) -> bool:
        return state.can_start(self.task_id, backend.time, self.machine_id)

    def resolve_machine(
        self, state: ScheduleState, backend: DESBackend
    ) -> MachineID:
        """Resolve the machine for the task given the current state of the schedule."""
        if self.machine_id != GLOBAL_MACHINE_ID:
            return self.machine_id

        return select_machine(state, self.task_id, backend.time)

    @override
    def process(self, state: ScheduleState, backend: DESBackend) -> None:
        time = backend.time

        if self.machine_id == GLOBAL_MACHINE_ID:
            self.machine_id = select_machine(state, self.task_id, time)

        state.assign_task(self.task_id, self.machine_id, time)


class SubmitEvent(ExecuteEvent):
    """Event representing the submission of a task to the schedule.

    This event is similar to ExecuteEvent but it is non-blocking, allowing the
    schedule to continue processing other events while the task is being submitted.

    Therefore, a feasible schedule can be generated by simply submitting all tasks
    in some order, and let the environment handle the execution and scheduling of
    the tasks based on their availability.

    This event logic is equivalent to the Parallel schedule generation scheme,
    where the queue is resolved by selecting from the set of eligible tasks at
    each time step.
    """

    blocking = False

    def __init__(
        self, task_id: TaskID, machine_id: MachineID = GLOBAL_MACHINE_ID
    ) -> None:
        """Initialize the SubmitEvent.

        Parameters
        ----------
        task_id: TaskID
            The ID of the task to be submitted.

        machine_id: MachineID, optional
            The ID of the machine on which to submit the task. If not specified,
            the event will attempt to resolve the machine at runtime.

        """
        super().__init__(task_id, machine_id)


class SkipEvent(SimulationEvent):
    """Event for skipping the current time to the next decision point.

    This event is also called NOOP in some other scheduling environments, it
    forces a skip in the current time after all events that can start in the
    current

    """

    blocking = True


class CheckpointEvent(SimulationEvent):
    """Event representing a checkpoint in the schedule."""

    time: Time

    def __init__(self, time: Time) -> None:
        self.time = time

    @override
    def is_ready(self, state: ScheduleState, backend: DESBackend) -> bool:
        return backend.time == self.time

    @override
    def process(self, state: ScheduleState, backend: DESBackend) -> None:
        return state.tight_global_time(backend.time)


class HaltEvent(SimulationEvent):
    """Event for halting the environment when processed."""

    blocking = True

    @override
    def process(self, state: ScheduleState, backend: DESBackend) -> None:
        backend.halt()


class NOOPEvent(SimulationEvent):
    """Event indicating that no other non-timed instruction must be executed."""

    blocking = True

    @override
    def process(self, state: ScheduleState, backend: DESBackend) -> None:
        next_time = state.get_next_decision_point(backend.time)

        backend.advance_to(next_time)


class CompleteEvent(SimulationEvent):
    """Wait for a task to complete to execute other instructions."""

    blocking = True
    task_id: TaskID

    def __init__(self, task_id: TaskID) -> None:
        self.task_id = task_id

    @override
    def earliest_time(self, state: ScheduleState) -> Time | None:
        return state.get_start_lb(self.task_id)

    @override
    def is_ready(self, state: ScheduleState, backend: DESBackend) -> bool:
        return state.is_fixed(self.task_id)

    @override
    def process(self, state: ScheduleState, backend: DESBackend) -> None:
        backend.advance_to(state.get_end(self.task_id))
