"""Implementation of events for the discrete event simulation environment."""

from typing_extensions import Self, override

from cpscheduler.environment.constants import (
    GLOBAL_MACHINE_ID,
    MachineID,
    TaskID,
    Time,
)
from cpscheduler.environment.des.base import Schedule, SimulationEvent
from cpscheduler.environment.state import ScheduleState


def select_machine(state: ScheduleState, task_id: TaskID) -> MachineID:
    """Select an available machine using a simple heuristic."""
    machines = state.get_machines(task_id)

    for machine in sorted(machines):
        if state.is_available(task_id, machine):
            return machine

    raise ValueError(f"No available machines for task {task_id}.")


class ExecuteEvent(SimulationEvent):
    """Event representing the execution of a task on a machine.

    This event triggers the start of a task's execution on a specific machine.
    It blocks the schedule until the task starts executing, ensuring that the task's
    execution is properly accounted for in the schedule's state.

    Resolution
    ----------
    If the machine_id is set to GLOBAL_MACHINE_ID, and there is only one machine
    available for the task, the event will be automatically resolved to that machine,
    creating another ExecuteEvent with the resolved machine_id.

    """

    blocking = True

    task_id: TaskID
    machine_id: MachineID

    def __init__(
        self, task_id: TaskID, machine_id: MachineID = GLOBAL_MACHINE_ID
    ) -> None:
        """Initialize the ExecuteEvent.

        Parameters
        ----------
        task_id: TaskID
            The ID of the task to be executed.

        machine_id: MachineID, optional
            The ID of the machine on which to execute the task. If not specified,
            the event will attempt to resolve the machine at runtime.

        """
        super().__init__()

        self.task_id = task_id
        self.machine_id = machine_id

    @override
    def resolve(self, state: ScheduleState) -> Self:
        machine_id = self.machine_id
        task_id = self.task_id
        task_machines = state.get_machines(task_id)

        if machine_id != GLOBAL_MACHINE_ID:
            if machine_id not in task_machines:
                raise ValueError(
                    f"Machine {machine_id} is not available for task {task_id}"
                )

        elif len(task_machines) == 1:
            # Statically resolve the machine if there is only one option
            resolved_machine = next(iter(task_machines))
            return type(self)(task_id, resolved_machine)

        return self

    @override
    def earliest_time(self, state: ScheduleState) -> Time:
        return state.get_start_lb(self.task_id, self.machine_id)

    @override
    def is_ready(self, state: ScheduleState) -> bool:
        return state.is_available(self.task_id, self.machine_id)

    @override
    def process(self, state: ScheduleState, schedule: Schedule) -> None:
        machine = self.machine_id
        if machine == GLOBAL_MACHINE_ID:
            machine = select_machine(state, self.task_id)

        state.execute_task(self.task_id, machine)


class SubmitEvent(ExecuteEvent):
    """Event representing the submission of a task to the schedule.

    This event is similar to ExecuteEvent but it is non-blocking, allowing the
    schedule to continue processing other events while the task is being submitted.

    Therefore, a feasible schedule can be generated by simply submitting all tasks
    in some order, and let the environment handle the execution and scheduling of
    the tasks based on their availability.

    This event logic is equivalent to the Parallel schedule generation scheme,
    where the queue is resolved by selecting from the set of eligible tasks at
    each time step.
    """

    blocking = False

    def __init__(
        self, task_id: TaskID, machine_id: MachineID = GLOBAL_MACHINE_ID
    ) -> None:
        """Initialize the SubmitEvent.

        Parameters
        ----------
        task_id: TaskID
            The ID of the task to be submitted.

        machine_id: MachineID, optional
            The ID of the machine on which to submit the task. If not specified,
            the event will attempt to resolve the machine at runtime.

        """
        super().__init__(task_id, machine_id)


class PauseEvent(SimulationEvent):
    """Event representing the interruption of a task's execution on a machine.

    This event triggers the pausing of a task's execution on a specific machine,
    when the task is currently executing.
    It blocks the schedule until the task is paused, ensuring that the task's
    execution is properly accounted for in the schedule's state.
    """

    blocking = True

    task_id: TaskID

    def __init__(self, task_id: int) -> None:
        """Initialize the PauseEvent.

        Parameters
        ----------
        task_id: TaskID
            The ID of the task to be paused.

        """
        super().__init__()

        self.task_id = task_id

    @override
    def is_ready(self, state: ScheduleState) -> bool:
        return state.is_executing(self.task_id)

    @override
    def process(self, state: ScheduleState, schedule: Schedule) -> None:
        state.pause_task(self.task_id)


class ResumeEvent(SimulationEvent):
    """Event representing the resumption of a paused task's execution on a machine.

    This triggers the resumption of a paused task's execution on the same
    machine it was executing on before being paused.
    It blocks the schedule until the task is resumed, ensuring that the task's
    execution is properly accounted for in the schedule's state.
    """

    blocking = True

    task_id: TaskID

    def __init__(self, task_id: int) -> None:
        """Initialize the ResumeEvent.

        Parameters
        ----------
        task_id: TaskID
            The ID of the task to be resumed.

        """
        super().__init__()

        self.task_id = task_id

    @override
    def is_ready(self, state: ScheduleState) -> bool:
        if state.is_paused(self.task_id):
            last_assignment = state.runtime.get_assignment(self.task_id)

            return state.is_available(self.task_id, last_assignment)

        return False

    @override
    def process(self, state: ScheduleState, schedule: Schedule) -> None:
        last_assignment = state.runtime.get_assignment(self.task_id)
        state.execute_task(self.task_id, last_assignment)


# FUTURE: Time advancement events are not yet fully tested, and may require
# adjustments to work the intended way in the schedule.
# The main reason is that blocking is only defined for non-timed events, and, as
# these events only produce checkpoints, they do not necessarily block the
# schedule until the time is advanced, as intended.
class CheckpointEvent(SimulationEvent):
    """Event representing a checkpoint in the schedule.

    This is a no-op, non-blocking event, mostly used for marking unskippable
    simulation times in the schedule.
    For example, it can be produced by a CompleteEvent at the end time of a task,
    to ensure that the schedule advances to at least that time.
    """

    blocking = False

    def __init__(self) -> None:
        """Initialize the CheckpointEvent."""
        super().__init__()


class CompleteEvent(SimulationEvent):
    """Event representing the completion of a task's execution.

    This event forces the environment to complete a task's execution, when
    the task is currently executing.
    It blocks the schedule until the task is completed.
    """

    blocking = True

    task_id: TaskID

    def __init__(self, task_id: int) -> None:
        """Initialize the CompleteEvent.

        Parameters
        ----------
        task_id: TaskID
            The ID of the task to be completed.

        """
        super().__init__()

        self.task_id = task_id

    @override
    def is_ready(self, state: ScheduleState) -> bool:
        return state.is_executing(self.task_id)

    @override
    def process(self, state: ScheduleState, schedule: Schedule) -> None:
        schedule.add_event(
            CheckpointEvent(), state, state.get_end_lb(self.task_id)
        )


class AdvanceTimeEvent(SimulationEvent):
    """Event representing the advancement of time in the schedule.

    This event triggers the advancement of time in the schedule by a specified
    amount.
    It blocks the schedule until the time is advanced, ensuring that the schedule
    properly accounts for the passage of time in its state.
    """

    blocking = True

    dt: Time

    def __init__(self, dt: Time) -> None:
        """Initialize the AdvanceTimeEvent.

        Parameters
        ----------
        dt: Time
            The amount of time to advance.

        """
        super().__init__()

        self.dt = dt

    @override
    def process(self, state: ScheduleState, schedule: Schedule) -> None:
        # Advance time by adding a no-op event at the target time
        schedule.add_event(CheckpointEvent(), state, state.time + self.dt)
